apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: airflow
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: airflow
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: 'https://airflow.apache.org'
        targetRevision: 1.15.0
        chart: airflow
        helm:
          values: |
            # Migration only runs once during bootstrap. Should to set false after that
            webserverSecretKey: '3b8e9fd606339fffe0eea1238c96e89f'
            fernetKeySecretName: 'airflow-fernet-key'
            createUserJob:
              useHelmHooks: false
            migrateDatabaseJob:
              enabled: true
              useHelmHooks: false
            registry:
              secretName: airflow-dockerconfig-secret
            data:
              brokerUrlSecretName: 'airflow-broker-url'
              metadataConnection:
                user: airflow_user
                pass: 'password123'
                protocol: postgresql
                host: data-airflow-cls.airflow-postgres.svc
                port: 5432
                db: airflow_db
                sslmode: disable
            ingress:
              web:
                enabled: true
                annotations:
                  kubernetes.io/ingress.class: nginx
                hosts:
                  - airflow.dataops
            extraConfigMaps:
              '{{ .Release.Name }}-airflow-variables':
                data: |
                  AIRFLOW_VAR_HELLO_MESSAGE: "Hi!"
                  AIRFLOW_VAR_KUBERNETES_NAMESPACE: "{{ .Release.Namespace }}"
              '{{ .Release.Name }}-airflow-variables-2':
                data: |
                  AIRFLOW_VAR_HELLO_MESSAGE: "Hi!"
                  AIRFLOW_VAR_KUBERNETES_NAMESPACE: "{{ .Release.Namespace }}"
            env:
              - name: AIRFLOW_ENV
                value: dataops
              - name: AIRFLOW_VAR_OUTPUT_FOLDER
                value: "/opt/airflow/data"
            workers:
              replicas: 1
              persistence:
                size: 500Mi
                storageClassName: 'standard'
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
              extraVolumes:
              - name: worker-output-folder-storage
                persistentVolumeClaim:
                  claimName: worker-output-folder
              extraVolumeMounts:
              - name: worker-output-folder-storage
                mountPath: /opt/airflow/data
                readOnly: false
            extraSecrets:
              airflow-ssh-secret:
                data: |
                  gitSshKey: 'UFVUX1NTSF9LRVlfVE9fR0lUX0hFUkUK'
            webserver:
              defaultUser:
                enabled: false
              replicas: 1
              resources:
                limits:
                  cpu: 500m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              livenessProbe:
                periodSeconds: 30
              readinessProbe:
                periodSeconds: 30
            scheduler:
              extraVolumes:
              - name: scheduler-output-folder-storage
                persistentVolumeClaim:
                  claimName: scheduler-output-folder
              extraVolumeMounts:
              - name: scheduler-output-folder-storage
                mountPath: /opt/airflow/data
                readOnly: false
              strategy:
                type: Recreate
              resources:
                limits:
                  cpu: 512m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
            redis:
              persistence:
                storageClassName: 'standard'
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              passwordSecretName: 'airflow-redis-password'
            postgresql:
              enabled: false
            config:
              core:
                dags_folder: '{{ include "airflow_dags" . }}'
                load_examples: 'False'
                executor: '{{ .Values.executor }}'
                colored_console_log: 'False'
                remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
              logging:
                remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
                colored_console_log: 'False'
              metrics:
                statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
                statsd_port: 9125
                statsd_prefix: airflow
                statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
              webserver:
                base_url: http://airflow.dataops
                cookie_samesite: Lax
                enable_proxy_fix: 'True'
                rbac: 'True'
                authenticate: 'True'
              celery:
                worker_concurrency: 2
              scheduler:
                # statsd params included for Airflow 1.10 backward compatibility; moved to [metrics] in 2.0
                statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
                statsd_port: 9125
                statsd_prefix: airflow
                statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
                # `run_duration` included for Airflow 1.10 backward compatibility; removed in 2.0.
                run_duration: 41460
              elasticsearch:
                json_format: 'True'
                log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"
              elasticsearch_configs:
                max_retries: 3
                timeout: 30
                retry_timeout: 'True'
              kerberos:
                keytab: '{{ .Values.kerberos.keytabPath }}'
                reinit_frequency: '{{ .Values.kerberos.reinitFrequency }}'
                principal: '{{ .Values.kerberos.principal }}'
                ccache: '{{ .Values.kerberos.ccacheMountPath }}/{{ .Values.kerberos.ccacheFileName }}'
              celery_kubernetes_executor:
                kubernetes_queue: 'kubernetes'
              kubernetes:
                namespace: '{{ .Release.Namespace }}'
                airflow_configmap: '{{ include "airflow_config" . }}'
                airflow_local_settings_configmap: '{{ include "airflow_config" . }}'
                pod_template_file: '{{ include "airflow_pod_template_file" . }}/pod_template_file.yaml'
                worker_container_repository: '{{ .Values.images.airflow.repository | default .Values.defaultAirflowRepository }}'
                worker_container_tag: '{{ .Values.images.airflow.tag | default .Values.defaultAirflowTag }}'
                multi_namespace_mode: '{{ if .Values.multiNamespaceMode }}True{{ else }}False{{ end }}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: airflow
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=false
