apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: airflow-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: airflow-secrets
    spec:
      project: default
      source:
        repoURL: https://github.com/13excite/dataops.git
        path: argocd/modules/airflow-secrets
        targetRevision: HEAD
        directory:
          jsonnet:
            extVars:
              - name: namespace
                value: 'airflow'
              - name: redis-password
                value: 'password123'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'airflow'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
